
import java.util.Scanner;

public class Converter{
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);

         System.out.println("****************************************************")
         System.out.println("Welcome to the convertor");
         System.out.println("****************************************************")
         System.out.println("Choose the currency you want to convert from:");
         System.out.println("1.Rands");
         System.out.println("2.Dollar");
         System.out.println("3.Euro");
         int choice = sc.nextInt();

    if(choice == 1 || choice ==2 || choice == 3){
        if(choice == 1){
            System.out.println("****************************************************");
            System.out.println("Enter the currency you want to convert to:");
            System.out.println("****************************************************");
            System.out.println("1.Dollar");
            System.out.println("2.Euro");
            int RandChoice = sc.nextInt();
            if(RandChoice == 1 || RandChoice == 2){
                if(RandChoice == 1){
                    
                }

            }else{
               System.out.println("choose from the given numbers");
            }
    }else if (choice == 2){

    }















    }
    
    else {
        System.out.println("choose from the given numbers");
    }}
    }



